- .tekton/v411-cnv-fbc-pull-request.yaml
- .tekton/v411-cnv-fbc-push.yaml
- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-push.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-push.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-push.yaml
Use CEL filtering annotation (see:
https://pipelinesascode.com/docs/guide/authoringprs/#advanced-event-matching ) to scope each application just to its specific directory (and the pipeline ones for consistency).
> Use CEL filtering to scope each pipeline to its directory

- v4.12/catalog/kubevirt-hyperconverged/catalog.yaml
- v4.12/graph.yaml
Add hco-bundle-registry:v4.12.7-19
> [v4.12] Add hco-bundle-registry:v4.12.7-19

- .tekton/v411-cnv-fbc-pull-request.yaml
- .tekton/v411-cnv-fbc-push.yaml
- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-push.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-push.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-push.yaml
- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-push.yaml
- pipelinesascode.tekton.dev/max-keep-runs: 3 -> 1 to avoid hitting pod number limit
- event == "push" -> event == "push" && target_branch == "main" to trigger the *-push pipelines only for push events to the main branch
> Optimize pipeline configuration

- .tekton/v411-cnv-fbc-pull-request.yaml
- .tekton/v411-cnv-fbc-push.yaml
- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-push.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-push.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-push.yaml
- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-push.yaml
Manually applying here
https://github.com/redhat-appstudio/build-definitions/pull/631
> add runAfter to fbc-validate task

- generate-fbc.sh
- v4.11/catalog/kubevirt-hyperconverged/catalog.json
- v4.12/catalog/kubevirt-hyperconverged/catalog.json
- v4.13/catalog/kubevirt-hyperconverged/catalog.json
- v4.14/catalog/kubevirt-hyperconverged/catalog.json
- v4.15/catalog/kubevirt-hyperconverged/catalog.json
This reverts commit 2c87361c6e5de98d56f923c951c9b7e8b1cdaecf.
> Revert "[test] consume bundle images from brew.registry.redhat.io"

- v4.14/catalog.Dockerfile
This reverts commit 6235583f513f5d24651b538262d5481e96f7bd92.
> Revert "[v4.14] getting ready for ose-operator-registry:v4.14"

- v4.11/devfile.yaml
- v4.12/devfile.yaml
- v4.13/devfile.yaml
- v4.14/devfile.yaml
- v4.15/devfile.yaml
- v4.16/devfile.yaml
Fix Dockerfile uri in devfile.yaml
for all the releases since RHTAP is now
corretly handling relative paths.
> Fix Dockerfile uri in devfile.yaml

- Makefile
- v4.14/graph.yaml
- v4.15/graph.yaml
- v4.16/graph.yaml
Correctly handle olm.skipRange delimiters.
Use the patience diff algorithm.
> Enhance diff with production

- .github/workflows/check-prod.yaml
Add an action to compare with production
released content.
> Add an action to compare with production

- v4.13/graph.yaml
Add hco-bundle-registry:v4.13.6.rhel9-102
> [v4.13] Add hco-bundle-registry:v4.13.6.rhel9-102

- v4.14/graph.yaml
Add hco-bundle-registry:v4.14.1.rhel9-62
> [v4.14] Add hco-bundle-registry:v4.14.1.rhel9-62

- v4.13/graph.yaml
Sync with production after the release of
hco-bundle-registry v4.13.6.rhel9-102
> [v4.13] Sync v4.13.6 with production

- v4.14/graph.yaml
Try to explicitly add
- v4.13.5 -> v4.14.1
- v4.13.6 -> v4.14.1 to test our capability to add explict
upgrade edges to already prod released
material.
> [v4.14] Explicitly add two upgrade edges

- v4.14/graph.yaml
auto update on 20231211T142338
> [v4.14] init v4.14.2

- v4.14/graph.yaml
Enable direct v4.13.6 -> v4.14.1
using only already production released material.
> [v4.14][test] Enable direct v4.13.6 -> v4.14.1

- v4.14/graph.yaml
This reverts commit d7d438f46844374bb201d71f614e25937298f291.
> Revert "[v4.14][test] Enable direct v4.13.6 -> v4.14.1"

- v4.14/graph.yaml
- v4.15/graph.yaml
- v4.16/graph.yaml
Align with production after the release
of v4.13.6 -> v4.14.1
> Align with production

- v4.14/graph.yaml
- v4.15/graph.yaml
- v4.16/graph.yaml
sync with prod after releasing v4.14.2
> sync with prod after releasing v4.14.2

- v4.12/graph.yaml
auto update on 20240123T052040
> [v4.12] Add hco-bundle-registry:v4.12.10-10

- v4.14/graph.yaml
- [v4.14] Add hco-bundle-registry:v4.14.4.rhel9-2
- Enable v4.14.3->v4.14.4
> [v4.14] Add hco-bundle-registry:v4.14.4.rhel9-2

- v4.14/graph.yaml
Sync hco-bundle-registry:v4.14.4.rhel9-256 with prod
Add hco-bundle-registry:v4.14.5.rhel9-27
> [v4.14] Add hco-bundle-registry:v4.14.5.rhel9-27

- v4.16/graph.yaml
Reverts openshift-cnv/cnv-fbc#5945
> Revert "[v4.16] Align with production released material"

- v4.15/graph.yaml
- v4.16/graph.yaml
- align with production after the release of v4.15.1.rhel9-132
- Add hco-bundle-registry:v4.15.2.rhel9-9
> [v4.15][v4.16] Add hco-bundle-registry:v4.15.2.rhel9-9

- v4.15/graph.yaml
This reverts commit c88d43c9388092ac2fe6151029755f35a2abe841.
> Revert "[v4.99] Add hco-bundle-registry:v4.99.0.rhel9-316"

- v4.15/graph.yaml
Add hco-bundle-registry:v4.15.2-183
> [v4.15] Add hco-bundle-registry:v4.15.2-183

- v4.17/graph.yaml
auto update on 20240704T073622
> [v4.17] Add hco-bundle-registry:v4.17.0.rhel9-72

- v4.14/graph.yaml
auto update on 20240722T142821
> [v4.14] Add hco-bundle-registry:v4.14.7.rhel9-272

- OWNERS
> Adding Axuba to OWNERS file

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
[v4.17] Add hco-bundle-registry:v4.17.0.rhel9-803
Add hco-bundle-registry:v4.17.0.rhel9-803
> [v4.17] Add hco-bundle-registry:v4.17.0.rhel9-803

- v4.12/rebuild.changelog
- v4.13/rebuild.changelog
- v4.14/rebuild.changelog
- v4.15/rebuild.changelog
- v4.16/rebuild.changelog
Adds a rebuild file on each version, this way we can trigger a rebuild of a specific version without having to update the catalog.
> Add rebuild files for missing versions

- v4.18/catalog.Dockerfile
This reverts commit ff7c6e70e4814c8da846fe50b5921c0737fe25e4.
> Reapply "Update catalog dockerfile base image"

- v4.18/catalog.Dockerfile
This reverts commit b3cf1a309bd4633c706bfba7b137b8cd161a9425.
> Revert "Reapply "Update catalog dockerfile base image""

- v4.14/graph.yaml
[v4.14] Add hco-bundle-registry:v4.14.9.rhel9-216
Add hco-bundle-registry:v4.14.9.rhel9-216
> [v4.14] Add hco-bundle-registry:v4.14.9.rhel9-216

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
[v4.17] Add hco-bundle-registry:v4.17.1.rhel9-81
Add hco-bundle-registry:v4.17.1.rhel9-81
> [v4.17] Add hco-bundle-registry:v4.17.1.rhel9-81

- v4.15/graph.yaml
[v4.15] Add hco-bundle-registry:v4.15.7.rhel9-252
Add hco-bundle-registry:v4.15.7.rhel9-252
> [v4.15] Add hco-bundle-registry:v4.15.7.rhel9-252

- v4.13/graph.yaml
[v4.13] Add hco-bundle-registry:v4.13.11.rhel9-437
Add hco-bundle-registry:v4.13.11.rhel9-437
> [v4.13] Add hco-bundle-registry:v4.13.11.rhel9-437

- v4.12/graph.yaml
[v4.12] Add hco-bundle-registry:v4.12.15-20
Add hco-bundle-registry:v4.12.15-20
> [v4.12] Add hco-bundle-registry:v4.12.15-20

- v4.14/graph.yaml
auto update on 20241204T093929
> [v4.14] Add hco-bundle-registry:v4.14.10.rhel9-137

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
[v4.17] Add hco-bundle-registry:v4.17.2.rhel9-114
Add hco-bundle-registry:v4.17.2.rhel9-114
> [v4.17] Add hco-bundle-registry:v4.17.2.rhel9-114

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
[v4.17] Add hco-bundle-registry:v4.17.3.rhel9-111
Add hco-bundle-registry:v4.17.3.rhel9-111
> [v4.17] Add hco-bundle-registry:v4.17.3.rhel9-111

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
- v4.17/updated_image.yaml
[v4.99] Add hco-bundle-registry:v4.99.0.rhel9-2153
Add hco-bundle-registry:v4.99.0.rhel9-2153
> [v4.99] Add hco-bundle-registry:v4.99.0.rhel9-2153(sprintly build v4.17)

- v4.18/catalog/kubevirt-hyperconverged/catalog.json
- v4.18/graph.yaml
[v4.18] Add hco-bundle-registry:v4.18.0.rhel9-849
Add hco-bundle-registry:v4.18.0.rhel9-849
> [v4.18] Add hco-bundle-registry:v4.18.0.rhel9-849

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
[v4.17] Add hco-bundle-registry:v4.17.5.rhel9-29
Add hco-bundle-registry:v4.17.5.rhel9-29
> [v4.17] Add hco-bundle-registry:v4.17.5.rhel9-29

- .tekton/fbc-pipeline.yaml
i saw that the task is failing on pulling the image of the buildah, so may adding a retry will reduce those issues
> add retries: 1 to the build task

- v4.17/catalog/kubevirt-hyperconverged/catalog.json
- v4.17/graph.yaml
- v4.17/updated_image.yaml
[v4.17] Add hco-bundle-registry:v4.17.10.rhel9-5
Add hco-bundle-registry:v4.17.10.rhel9-5
> [v4.17] Add hco-bundle-registry:v4.17.10.rhel9-5 on stable channel

- .tekton/fbc-pipeline.yaml
- .tekton/v420-cnv-fbc-pull-request.yaml
- .tekton/v420-cnv-fbc-push.yaml
More info in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1749674476926729
> Temporarily skip fips check on v4.20 until fixed
