- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-push.yaml
Use CEL filtering annotation (see:
https://pipelinesascode.com/docs/guide/authoringprs/#advanced-event-matching ) to scope each application just to its specific directory (and the pipeline ones for consistency).
> [v4.15] Use CEL filtering to scope each pipeline to its directory

- .tekton/v411-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
Double image-expires-after from 5d to 10d
to get a larger recovery time in case of failures
with the release pipeline.
> Double image-expires-after on *-pull-request pipelines

- .github/workflows/pr-sanity.yaml
Catalogs generated by opm v1.28.0 and newer
are not compatible with OCP v4.13 and older.
Force opm v1.27.1 for backward compatibily.
TODO: use OCP dependant opm version
> Force opm v1.27.1 for backward compatibility

- v4.13/graph.yaml
manual update to get ready to push to production.
> [v4.13] Revert to hco-bundle-registry:v4.13.7.rhel9-315

- v4.15/graph.yaml
Correctly using registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.15 as its base image.
> [v4.15] Add hco-bundle-registry:v4.15.0.rhel9-2585

- v4.15/graph.yaml
Correctly using registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.15 as its base image.
> [v4.15] Add hco-bundle-registry:v4.15.0.rhel9-2670

- v4.16/catalog.Dockerfile
Apparently, RHTAP/KonFlux can't use the brew registry in the release pipeline, so we're reverting back to production v4.15 to unblock 4.16 stage releases
> [v4.16] Revert back to `registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.15`

- v4.15/graph.yaml
Get ready to push out v4.99.0.rhel9-316 on dev-preview channel without pushing out any v4.15.2 on the stable one.
> [v4.15] Get ready to push out v4.99.0.rhel9-316 on dev-preview channel

- Makefile
- v4.15/graph.yaml
4.99 bundles are designed to be replaced with fresh ones in the dev-preview channel, not being accumulated over time
> ignore 4.99 modification on check-prod

- .github/workflows/check-prod.yaml
Use paths-ignore directive to avoid running
check-prod sanity actions when the PR contains
only changes to files under .tekton/ .
This will prevent an outdated configuration of the repo
to block pipelines updates that can then eventually
block repo updates with a deadlock.
> skip check-prod when only .tekton/ is touched

- Makefile
hco-bundle-registry v4.99.0.rhel9-316
got erroneously shipped with:
skipRange: <v4.99.0
while the correct syntax would be:
skipRange: <4.99.0
Let's tolerate PRs that are going to fix it
in the next release.
Once this will be effectively fixed also in production, this PR could PR reverted.
> Tolerate fixes on `skipRange: <v4.99.0`

- Makefile
- v4.17/catalog.Dockerfile
Reverts openshift-cnv/cnv-fbc#9826
looks like this change has caused a deletion of 4.17 graph.yaml:
https://github.com/openshift-cnv/cnv-fbc/commit/f2dbde1c8ac5afe107911f2e35d2afd2fde0ba09
> Revert "Use operator registry image of 4.17 for v4.17"

- .tekton/v411-cnv-fbc-pull-request.yaml
- .tekton/v411-cnv-fbc-push.yaml
- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-push.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-push.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-push.yaml
- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-push.yaml
- .tekton/v416-cnv-fbc-pull-request.yaml
- .tekton/v416-cnv-fbc-push.yaml
- .tekton/v417-cnv-fbc-pull-request.yaml
- .tekton/v417-cnv-fbc-push.yaml
in 0.2, the 'BASE_IMAGES_DIGESTS' is no longer supported. all of its references should be removed, as advised here: https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
Currently, all pull-requests CI are failing due to that.
> Remove BASE_IMAGES_DIGESTS due to migration to konflux-ci 0.2

- Makefile
In the past we uncorrectly used
`skipRange: <v4.99.0` for v4.99 sprintly releases. Now we are more correctly setting something like
`skipRange: <4.99.0-0.1724436925`.
Let's fix `make check-prod` to tollerate both
the expressions.
> Fix check-prod for v4.99 skipRange

- .tekton/v412-cnv-fbc-pull-request.yaml
- .tekton/v412-cnv-fbc-push.yaml
- .tekton/v413-cnv-fbc-pull-request.yaml
- .tekton/v413-cnv-fbc-push.yaml
- .tekton/v414-cnv-fbc-pvfh-pull-request.yaml
- .tekton/v414-cnv-fbc-pvfh-push.yaml
- .tekton/v415-cnv-fbc-gnu1-pull-request.yaml
- .tekton/v415-cnv-fbc-gnu1-push.yaml
- .tekton/v416-cnv-fbc-pull-request.yaml
- .tekton/v416-cnv-fbc-push.yaml
- .tekton/v417-cnv-fbc-pull-request.yaml
- .tekton/v417-cnv-fbc-push.yaml
This reverts commit 61bc282537e4dd032363fe5491e0d5e6c64e0ab3.
quay.io/redhat-appstudio-tekton-catalog/task-fbc-validation d959d58 is failing extracting the target OCP release from the BASE_IMAGE value. Let's skip it until it's fixed, see:
https://github.com/konflux-ci/build-definitions/pull/1373
> Revert "Update Konflux references to d959d58"

- .github/workflows/check-prod.yaml
- .gitignore
- Makefile
Till now, make check-prod was comparing all the versions against prod in a single execution so a broken
version was blocking also all
the other y-streams.
Let's decouple it checking only the versions touched in the PR.
> [check-prod] decouple versions while comparing with prod

- .github/renovate.json
The tag specified for the ose-operator-registry image, is also implicitly used to select the target OCP
minor we intend to release to.
See: https://konflux-ci.dev/architecture/ADR/0026-specifying-ocp-targets-for-fbc.html Let's ensure that mintmaker is not going to bump
it to ensure we are going to release on the
expected OCP minor.
> Configure mintmaker to avoid bumping ose-operator-registry

- v4.16/catalog.Dockerfile
- v4.17/catalog.Dockerfile
Images:
- registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16
- registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17 
are now publicly available.
Use the released images from the prod registry.
> Use ose-operator-registry-rhel9 from prod

- v4.14/graph.yaml
it appears the IIB build of this bundle is missing
> [v4.14] [manual] Add hco-bundle-registry:v4.14.9.rhel9-216

- generate-fbc.sh
@tiraboschi This change uses a `skopeo` formatting flag to extract the `url` field value without the need to generate all fields and then filter with grep.
I've tested it locally and it generated the same output.
PD: I've used this repo as reference to generate our equivalent RHDH `orchestrator-fbc` that I wanted to contribute something back after all the work I've benefited from by this repository.
> Use --format in skopeo to extract container label  instead of using grep

- generate-fbc.sh
Sometimes the image registry is not able to process our request, which causes the whole script to fail. This PR fixes this by implementing a retry system that will keep trying X number of times in case the registry is no able to respond.
> Improve image check resilience

- v4.15/graph.yaml
As in https://github.com/openshift-cnv/cnv-fbc/pull/16778 to generate a fresh snapshot with FIPS validation task enabled.
Fixes: https://issues.redhat.com/browse/CNV-56950
> [v4.15] Add a direct v4.14.6 -> v4.15.8

- .tekton/fbc-pipeline.yaml
- v4.19/rebuild.changelog
An automatic mintmaker update bumped one of the tasks to 0.2
https://github.com/openshift-cnv/cnv-fbc/commit/a4535d6e806d98839d4519fa3bfa39f4451e39ed#diff-23c6b15db160f8e1c4b1a155c1a105208cf442b8769d82b7869bae6c00ff46d1R310-R311
But it didn't apply the migration steps
https://github.com/konflux-ci/build-definitions/blob/main/task/apply-tags/0.2/MIGRATION.md
> Fix apply task update
